FROM bellsoft/liberica-openjdk-alpine:11.0.16.1-1

COPY ../.. ./src

RUN mkdir ./out

RUN javac -sourcepath ./src -d out src/Lesson1/Homework1/sample/Main.java

CMD java -classpath ./out Lesson1.Homework1.sample.Main